FROM python:3.8-slim-buster
RUN pip install --upgrade pip

WORKDIR /src
COPY ./src /src
# Install dependencies:
COPY requirements.txt .
RUN pip install -e /src/lib/libcloud
RUN pip install -r requirements.txt
EXPOSE 3003
COPY /src/app_google_drive.py .
# Run the application:
CMD gunicorn --bind 0.0.0.0:3003 app_google_drive:app