FROM python:3.8-slim-buster
RUN pip install --upgrade pip

WORKDIR /src
COPY ./src /src
# Install dependencies:
COPY requirements.txt .
RUN pip install -e /src/lib/libcloud
RUN pip install -r requirements.txt
EXPOSE 3004
COPY /src/app_ipfs.py .
# Run the application:
CMD gunicorn --bind 0.0.0.0:3004 --preload --workers 8 --worker-class gevent app_ipfs:app
#CMD python app_ipfs.py